version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mail_project_app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://mailo:mailo@db:5432/mailo_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mail_project_db
    environment:
      POSTGRES_USER: mailo
      POSTGRES_PASSWORD: mailo
      POSTGRES_DB: mailo_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: